### ISSUE TITLE
SYNC IS NOT AVAILABLE

### ISSUE THREAD

**Issue by ashwinee2591** [brave/sync#368]
Unable to sync anything on desktop and mobile too.
![Bug](https://user-images.githubusercontent.com/58855419/74726631-ce079780-5265-11ea-95fa-227b3deed2d2.JPG)

**Comment by eiswuerfel** [comment]
https://github.com/brave/brave-browser/issues/8293

Release Notes V1.3.115
Fixed several crashes and stability issues by temporarily disabling sync. (#7781)

**Comment by shnbwmn** [comment]
Any ETA on when we might expect this functionality to return?

**Comment by scottzach1** [comment]
Apologies I can't give any level of insight as I am not part of the project.
You may, however, be interested in watching the teams progress unfold on the 'sync' project board.

[brave/brave-browser/projects/14](https://github.com/brave/brave-browser/projects/14)

**Comment by palanthis** [comment]
Still not working. Do you guys need help with this?

**Comment by Turki-fd** [comment]
Still not fixed. I can't believe that more than 4 months have passed and the problem still occurs. Brave, PLEASE do something.

**Comment by scottzach1** [comment]
> Still not fixed. I can't believe that more than 4 months have passed and the problem still occurs. Brave, PLEASE do something. 

They have been. In fact, if you download the nightly releases it is enabled by default. Otherwise I believe on the standard leases you can enable it in the flags (brave://flags).

Personally I have really happy with how they have implemented it. Works really well for me.
